Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Vette.Location': ['NodeTypes/*']
    Ui:
      frontendDevelopmentMode: true
      resources:
        javascript:
          'Vette.Location.LocationEditor':
            resource: resource://Vette.Location/Public/LocationEditor/Plugin.js